[project]
name = "slitherlink"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.16"
dependencies = [
    "pillow>=11.1.0",
    "python-sat>=1.8.dev14",
    "sv-ttk>=2.6.0",
]

[dependency-groups]
dev = [
    "beautifulsoup4>=4.13.3",
]
