name: Run Evaluation on Main

on:
  push:
    branches:
      - main

jobs:
  run_evaluation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Run evaluation script
      run: python src/evaluation.py

    - name: Write to report.csv and push to reports branch
      run: |
        git checkout -b report
        # Assuming the evaluation script generates a report.csv file
        git add reports.csv -f
        git commit -m "Add evaluation report ({sha})"
        git push origin report
